### ISSUE TITLE
[BUG] script fails to do batch downloads, throws error (ERROR: read ECONNRESET)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#126]
** Main info: **

Script version: 4.12.5
Show ID: 1400119 (does this for other shows to)
Episode ID: 1-12
Command used: funi -s 1400119 --mks --dub enUS -e 1-12

Console output: 
```text
[INFO] 530 of 715 parts downloaded [74%] (34s)
[INFO] 540 of 715 parts downloaded [76%] (32s)
[INFO] 550 of 715 parts downloaded [77%] (31s)
[INFO] 560 of 715 parts downloaded [78%] (29s)
[WARN] Part 556: 2 attempt to retrieve data
	ERROR: read ECONNRESET
/Users/USER/Apps/Animie/anidl/funimation-downloader-nx/node_modules/p-cancelable/index.js:48
					throw new Error('The `onCancel` handler was attached after the promise settled.');
					      ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/USER/Apps/Animie/anidl/funimation-downloader-nx/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/Users/USER/Apps/Animie/anidl/funimation-downloader-nx/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/Users/USER/Apps/Animie/anidl/funimation-downloader-nx/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:510:26)
    at Request.emit (node:events:390:28)
    at Timeout.retry (/Users/USER/Apps/Animie/anidl/funimation-downloader-nx/node_modules/got/dist/source/core/index.js:1264:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

** Additional Info: **

this is starting to become frustrating whenever I do batch downloads it throws the above error every 2-3 episodes
it may be random, however when it occurs it doesn't auto-resume or anything, this makes it difficult for mass downloads when I leave it overnight & when I get back on to see it got stuck on EP 3.

**Comment by DragonVsKira** [comment]
if it random it will be hard to test

**Comment by izu-co** [comment]
Since we merged both downloaders, your issue may be invalid. Please check and reopen if this issue persists.
