### ISSUE TITLE
error when downloading

### ISSUE THREAD

**Issue by OryWareKyrie** [anidl/multi-downloader-nx#162]
hi manin @izu-co, how are you?
I'm getting this error downloading funimation and crunchyroll on a vps
```
...
[INFO] 350 of 710 parts downloaded [49%] (26s)
[INFO] 400 of 710 parts downloaded [56%] (22s)
[INFO] 450 of 710 parts downloaded [63%] (19s)
[WARN] Part 488: 2 attempt to retrieve data
        ERROR: read ECONNRESET
E:\multi-downloader-nx\node_modules\p-cancelable\index.js:48
                                        throw new Error('The `onCancel` handler was attached after the promise settled.');
                                              ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (E:\multi-downloader-nx\node_modules\p-cancelable\index.js:48:12)
    at makeRequest (E:\multi-downloader-nx\node_modules\got\dist\source\as-promise\index.js:38:13)
    at Request.<anonymous> (E:\multi-downloader-nx\node_modules\got\dist\source\as-promise\index.js:143:17)
    at Object.onceWrapper (node:events:510:26)
    at Request.emit (node:events:390:28)
    at Timeout.retry (E:\multi-downloader-nx\node_modules\got\dist\source\core\index.js:1264:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
[Full](https://github.com/anidl/multi-downloader-nx/files/7532689/Debug.txt)
I noticed that the bigger the `--partsize` the faster this error happens. tested with `--partsize 1` and so far no error.
I was looking for the .txt after the debug inside the folders but I couldn't find it. @izu-co the tool is not generating the txt?

thanks for your work 👍👏🖖

**Comment by izu-co** [comment]
Can you give me the command used as well?

**Comment by OryWareKyrie** [comment]
> Can you give me the command used as well?

node index.js --service crunchy -s GRQ4CZD8P -e 01-14 --allSubs --partsize 50 -q 6

**Comment by izu-co** [comment]
Will look at it soon

**Comment by izu-co** [comment]
I just tested it and I don't get the error.

**Comment by OryWareKyrie** [comment]
> I just tested it and I don't get the error.

strange. I'm thinking it's the 1GB/s connection because even setting --partsize 50 is going fast.
```
E:\multi-downloader-nx\lib>node index.js --service funi -s 1626834 -e 15-17 --allSubs --dub jaJP --simul --partsize 50 -q 10

=== Multi Downloader NX 1.0.3 ===

[#1626834] Scarlet Nexus (2021)
[0001] Scarlet Nexus - #01 Scarlet Psionics (00:24:04) [HD1080, Spanish, Portuguese, Japanese]
[0002] Scarlet Nexus - #02 Scarlet Guardians (00:24:04) [HD1080, Spanish, Portuguese, Japanese]
[0003] Scarlet Nexus - #03 Conspiracy (00:24:04) [HD1080, Japanese, Spanish, Portuguese]
[0004] Scarlet Nexus - #04 Red Strings (00:24:04) [HD1080, Spanish, Portuguese, Japanese]
[0005] Scarlet Nexus - #05 Karen's Revolt (00:24:04) [SD540, Portuguese, Spanish, Japanese]
[0006] Scarlet Nexus - #06 A Doomed Tomorrow (00:24:04) [SD540, Japanese, Spanish, Portuguese]
[0007] Scarlet Nexus - #07 The Hunt for Nagi (00:24:04) [SD540, Portuguese, Japanese, Spanish]
[0008] Scarlet Nexus - #08 The Hospital's Secrets (00:24:04) [SD540, Portuguese, Spanish, Japanese]
[0009] Scarlet Nexus - #09 A Dubious Wonder Drug (00:24:04) [SD540, Spanish, Portuguese, Japanese]
[0010] Scarlet Nexus - #10 The Rebel Yuito (00:24:04) [HD1080, Japanese, Portuguese, Spanish]
[0011] Scarlet Nexus - #11 Togetsu (00:24:05) [HD1080, Japanese, Spanish, Portuguese]
[0012] Scarlet Nexus - #12 The Moon's Secrets (00:24:04) [HD1080, Japanese, Spanish, Portuguese]
[0013] Scarlet Nexus - #13 The Design Children (00:24:04) [HD1080, Japanese, Spanish, Portuguese]
[0014] Scarlet Nexus - #14 A 2,000-Year Ambition (00:24:04) [HD1080, Japanese, Portuguese, Spanish]
[0015] Scarlet Nexus - #15 Nagi Attacks (00:24:05) [HD1080, Japanese, Spanish, Portuguese] (selected)
[0016] Scarlet Nexus - #16 Naomi and Alice (00:24:04) [HD1080, Japanese] (selected)
[0017] Scarlet Nexus - #17 Arahabaki's Trap (00:24:05) [HD1080, Japanese] (selected)
[0018] Scarlet Nexus - #18 Karen's Wish (00:24:04) [HD1080, Japanese]
[0019] Scarlet Nexus - #19 Kagero's Confession (00:24:05) [HD1080, Japanese]
[0020] Scarlet Nexus - #20 Together Again (00:24:05) [HD1080, Japanese]

[INFO] Selected Episodes: 0015, 0016, 0017

[INFO] Scarlet Nexus - S1E15 - Nagi Attacks
[INFO] Available streams (Non-Encrypted):
[#2809508] Japanese [Simulcast] (selected) (using 'English' for subtitles)
[#3950751] Portuguese (Brazil) [Simulcast]
[#3950750] Spanish (Latin Am) [Simulcast]
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (461KiB/s)
         2: 640x360 (736KiB/s)
         3: 768x432 (1147KiB/s)
         4: 768x432 (1572KiB/s)
         5: 960x540 (2703KiB/s)
         6: 1280x720 (3830KiB/s)
         7: 1280x720 (5678KiB/s)
         8: 1920x1080 (7368KiB/s)
         9: 1920x1080 (9520KiB/s)
[INFO] Selected layer: 9 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2425927/4923f037-9048-4dfe-8fdb-ffefdc7dc0festrnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjQyNTkyNy8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2ODQyMjk5fX19XX0_&Signature=qzU5cIEHlnzHWclaWKI0mJZG2I~ZEfKjFm6fM0w3zvVb55KrDTGipX455uLC21xQ88FEqeohOMctbRyeMlc7Pjkj156TvnXwHVvyBi60lGg5Mgm-aAmqlUtDyiF0mO2nXDWd-NvS5dr0TjyDFk~6E277pYZ-oj1JzQwPPcmpVhRJ1091OfTGlbR-XMOiC7WI8~gGX9paxwMmfu9cYCUQ1xe7-jOAoAhDAfhD60TJ~ulFlHAtFdOfAntQxPxbnngX6uds9pGxbKNoHAb7hoW58ZQbUX~FCldKa1YvpKsuVHeZwoYOGz6v32vXUjNEC~Ggs-h1FSsPsHEbQ5OAya6jeA__&rt=1445027
[INFO] Output filename: [Funimation] Scarlet Nexus - 15 [1080p].ts
[INFO] Saving stream to «E:\multi-downloader-nx\lib\videos\[Funimation] Scarlet Nexus - 15 [1080p].video.ts»...
[INFO] 50 of 723 parts downloaded [7%] (38s)
[INFO] 100 of 723 parts downloaded [14%] (33s)
[INFO] 150 of 723 parts downloaded [21%] (30s)
[INFO] 200 of 723 parts downloaded [28%] (27s)
[INFO] 250 of 723 parts downloaded [35%] (33s)
[INFO] 300 of 723 parts downloaded [41%] (28s)
[INFO] 350 of 723 parts downloaded [48%] (24s)
[INFO] 400 of 723 parts downloaded [55%] (20s)
[INFO] 450 of 723 parts downloaded [62%] (17s)
[INFO] 500 of 723 parts downloaded [69%] (13s)
[INFO] 550 of 723 parts downloaded [76%] (10s)
[INFO] 600 of 723 parts downloaded [83%] (7s)
[INFO] 650 of 723 parts downloaded [90%] (4s)
[INFO] 700 of 723 parts downloaded [97%] (1s)
[INFO] 723 of 723 parts downloaded [100%] (0s)
[INFO] Saving stream to «E:\multi-downloader-nx\lib\videos\[Funimation] Scarlet Nexus - 15 [1080p].audio.ja.ts»...
[INFO] 50 of 726 parts downloaded [7%] (7s)
[INFO] 100 of 726 parts downloaded [14%] (31s)
[INFO] 150 of 726 parts downloaded [21%] (32s)
[INFO] 200 of 726 parts downloaded [28%] (22s)
[INFO] 250 of 726 parts downloaded [34%] (21s)
[WARN] Part 267: 2 attempt to retrieve data
        ERROR: read ECONNRESET
E:\multi-downloader-nx\node_modules\p-cancelable\index.js:48
                                        throw new Error('The `onCancel` handler was attached after the promise settled.');
                                              ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (E:\multi-downloader-nx\node_modules\p-cancelable\index.js:48:12)
    at makeRequest (E:\multi-downloader-nx\node_modules\got\dist\source\as-promise\index.js:38:13)
    at Request.<anonymous> (E:\multi-downloader-nx\node_modules\got\dist\source\as-promise\index.js:143:17)
    at Object.onceWrapper (node:events:510:26)
    at Request.emit (node:events:390:28)
    at Timeout.retry (E:\multi-downloader-nx\node_modules\got\dist\source\core\index.js:1264:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by izu-co** [comment]
I've traced this issue back to be related to `got`. I will try to implement a work around.

**Comment by OryWareKyrie** [comment]
> I've traced this issue back to be related to `got`. I will try to implement a work around.

Ok! Thanks!!!

**Comment by izu-co** [comment]
@OryWareKyrie Can you try the newest release?

**Comment by OryWareKyrie** [comment]
> @OryWareKyrie Can you try the newest release?

apparently yes. thank you very much manin.

**Comment by izu-co** [comment]
Glad it helped.
