### ISSUE TITLE
[BUG] [Funimation/Crunchy] Crunchy  --novids being ignored?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#175]
** Main info: **

Script version: Multi Downloader NX 2.0.0
Service: crunchy
Show ID: GY9PC2WJE
Episode ID: 0011|G9DUED403
Command used: aniDL --service crunchy -s GY9PC2WJE -e 11 --novids   (I use the alias "aniDL" for the command)

Console output: 
```text
❯ aniDL --service crunchy -s GY9PC2WJE -e 11 --novids

=== Multi Downloader NX 2.0.0 ===

[INFO] USER: XxUnkn0wnxX
[INFO] Your Country: AU

  [S:GY9PC2WJE] The Hidden Dungeon Only I Can Enter (English Dub) (Season: 1) [DUB]
  [0001|E:GQJUGD38P] 1 - Powerful Skill Set [24m27s, DUB, STREAM]
    - Subtitles: en
  [0002|E:G14U431W0] 2 - The Guild and the Receptionist [24m27s, DUB, STREAM]
    - Subtitles: en
  [0003|E:GK9U3ZE43] 3 - The Troubled Classmate [24m27s, DUB, STREAM]
    - Subtitles: en
  [0004|E:GWDU8PV95] 4 - The Untainted Cleric [24m27s, DUB, STREAM]
    - Subtitles: en
  [0005|E:G4VUQM0JM] 5 - The Future of This Harem [24m27s, DUB, STREAM]
    - Subtitles: en
  [0006|E:GG1U2DVJ8] ☆ 6 - The Tulip Lion [24m27s, DUB, STREAM]
    - Subtitles: en
  [0007|E:GEVUZ8ZMW] ☆ 7 - The Receptionist Ranking [24m27s, DUB, STREAM]
    - Subtitles: en
  [0008|E:GMKUX5EEV] ☆ 8 - A Little Girl's Wish [24m12s, DUB, STREAM]
    - Subtitles: en
  [0009|E:GK9U38G4K] ☆ 9 - To the Gala [24m12s, DUB, STREAM]
    - Subtitles: en
  [0010|E:GG1U2D1KZ] ☆ 10 - Let's Go to the Hot Springs [24m12s, DUB, STREAM]
    - Subtitles: en
 ✓[0011|E:G9DUED403] ☆ 11 - Noir's Decision [24m12s, DUB, STREAM]
    - Subtitles: en
  [0012|E:GG1U2DP7G] ☆ 12 - A Battle I Can't Lose [24m12s, DUB, STREAM]
    - Subtitles: en

[INFO] Requesting: [G9DUED403] The Hidden Dungeon Only I Can Enter (English Dub) - 11 - Noir's Decision
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/eng/- )
[INFO] Full stream found! ( 2: download_hls/eng/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/eng/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/a0380baee29e410177bd9b4f1cd4ffb7/assets/fe157737359ed057bbd8aca438804e4e_,4048103.mp4,4048104.mp4,4048102.mp4,4048100.mp4,4048101.mp4,4048099.mp4,.urlset/master.m3u8?Expires=1637807682&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9hMDM4MGJhZWUyOWU0MTAxNzdiZDliNGYxY2Q0ZmZiNy9hc3NldHMvZmUxNTc3MzczNTllZDA1N2JiZDhhY2E0Mzg4MDRlNGVfLDQwNDgxMDMubXA0LDQwNDgxMDQubXA0LDQwNDgxMDIubXA0LDQwNDgxMDAubXA0LDQwNDgxMDEubXA0LDQwNDgwOTkubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Mzc4MDc2ODJ9fX1dfQ__&Signature=UnT3ivM95pB3SXGeZ2pnHMlG3C0TpAKjI2AUYn5Tai0jx1dCrwFFsxtQvN1oHE4XTgYijbX0-QhfpdXbK~sv4W0cLEG7TD4SFMM5e2YLZ48VObzVY1~hSUeVbmpV8Fw5~B2ZLS8PcyOe5HFCw-qR8rlYGfNxrU3sRFlY~6vCuDvpK52klTDqlxwma0rmvR8iNMmmNG7fkQC4vBzQpJSjMSupLtjpVePpE2kdjupONKC0LjMdwiAwnbn5MI40ULYKV4MFQnrgXN0FTNge1MYF1Igr7F1~LNiVYF~68atBAHNjO8G~1bo~cAa44qSj4Aq1QkNMn1SW7M~f73hwYUxf3Q__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/eng/-)
[INFO] Servers available:
	pl.crunchyroll.com (ll-prod)
	pl.crunchyroll.com (fy-prod)
[INFO] Available qualities:
	[1] 144x80 (191KiB/s)
	[2] 428x240 (549KiB/s)
	[3] 640x360 (1067KiB/s)
	[4] 848x480 (2041KiB/s)
	[5] 1280x720 (4024KiB/s)
	[6] 1920x1080 (7919KiB/s)
[INFO] Selected quality: 1920x1080 @ pl.crunchyroll.com (ll-prod)
[INFO] Output filename: [CR] The Hidden Dungeon Only I Can Enter (English Dub) - 11 [1080p]
[INFO] Total parts in stream: 726 (19*40)
[INFO] Saving stream to «/Users/USER/Downloads/AppDL/aniDL/[CR] The Hidden Dungeon Only I Can Enter (English Dub) - 11 [1080p].ts»...
[INFO] 40 of 726 parts downloaded [6%] (2m53s | 7.9Mb/s)
```

** Additional Info: **
so now I cannot just download subs? I have to Dl video as well?
also, why use the beta api? here in AU we don't even have beta page yet..

the old crunchy script worked fine for --novids 

Looks nicer compared to using beta API mess
```text
❯ crunch -s 25501 -e 11 --novids

=== Crunchyroll Downloader NX 5.3.2 ===

[S:25501] The Hidden Dungeon Only I Can Enter (English Dub) 
[URL] https://www.crunchyroll.com/syndication/feed?type=episodes&id=25501
  [0001|M0808425] 1 - Powerful Skill Set
   - PubDate: 2021-02-26 11:00:00 UTC
   - Subtitles: en
  [0002|M0808580] 2 - The Guild and the Receptionist
   - PubDate: 2021-03-05 11:00:00 UTC
   - Subtitles: en
  [0003|M0809009] 3 - The Troubled Classmate
   - PubDate: 2021-03-12 11:00:00 UTC
   - Subtitles: en
  [0004|M0809459] 4 - The Untainted Cleric
   - PubDate: 2021-03-19 10:00:00 UTC
   - Subtitles: en
  [0005|M0810050] 5 - The Future of This Harem
   - PubDate: 2021-03-26 10:00:00 UTC
   - Subtitles: en
  [0006|M0810694] 6 - The Tulip Lion
   - PubDate: 2021-04-02 10:00:00 UTC
   - Subtitles: en
  [0007|M0811034] 7 - The Receptionist Ranking
   - PubDate: 2021-04-09 10:00:00 UTC
   - Subtitles: en
  [0008|M0811289] 8 - A Little Girl's Wish
   - PubDate: 2021-04-16 10:00:00 UTC
   - Subtitles: en
  [0009|M0811446] 9 - To the Gala
   - PubDate: 2021-04-23 10:00:00 UTC
   - Subtitles: en
  [0010|M0811840] 10 - Let's Go to the Hot Springs
   - PubDate: 2021-04-30 10:00:00 UTC
   - Subtitles: en
 ✓[0011|M0812147] 11 - Noir's Decision
   - PubDate: 2021-05-07 10:00:00 UTC
   - Subtitles: en
  [0012|M0812345] 12 - A Battle I Can't Lose
   - PubDate: 2021-05-14 10:00:00 UTC
   - Subtitles: en

[INFO] Requesting: [812147] The Hidden Dungeon Only I Can Enter (English Dub) - 11 - Noir's Decision

[INFO] PAGE MSGs:
  [NAG] The 1000th episode of One Piece airs is AVAILABLE NOW! Don't miss the latest episode of this Shonen classic and click HERE to catch up now! 

[INFO] Your region: AU Australia
[INFO] Your account: XxUnkn0wnxX 

[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/eng/- )
[INFO] Full stream found! ( 2: multitrack_adaptive_hls_v2/eng/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/eng/- )
[INFO] Downloading video...
[INFO] Playlists URL: [HIDDEN] (adaptive_hls/eng/-)
[INFO] Downloading skipped!
[INFO] Subtitle downloaded: [CR] The Hidden Dungeon Only I Can Enter (English Dub) - 11 [1080p].01 eng English.ass
[INFO] TS file not found, skip muxing video...
```

Old Script Clean Look:
<img width="1242" alt="Screen Shot 2021-11-23 at 1 44 13 pm" src="https://user-images.githubusercontent.com/2242880/142964211-b2afe04b-61d8-4bda-b4a8-ec6b61b9105a.png">

New Multi DL Script (Very Messy for results screen IMO)
<img width="1242" alt="Screen Shot 2021-11-23 at 1 44 54 pm" src="https://user-images.githubusercontent.com/2242880/142964247-aedbfa88-1d12-4710-be49-67e3441f0bef.png">

**Comment by izu-co** [comment]
This is of course unintended. I will look at it later today

**Comment by izu-co** [comment]
About the new beta look - I agree that it is not as nice, abut I think that we should give as much detail as possible.

**Comment by izu-co** [comment]
It is fixed btw.

If you have an idea for a better design let me know.

**Comment by XxUnkn0wnxX** [comment]
@izu-co it works howver i get error now at the end..

`TypeError: Cannot read properties of undefined (reading 's')`

```text
[INFO] Requesting: [G9DUED403] The Hidden Dungeon Only I Can Enter (English Dub) - 11 - Noir's Decision
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/eng/- )
[INFO] Full stream found! ( 2: download_hls/eng/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/eng/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/a0380baee29e410177bd9b4f1cd4ffb7/assets/fe157737359ed057bbd8aca438804e4e_,4048103.mp4,4048104.mp4,4048102.mp4,4048100.mp4,4048101.mp4,4048099.mp4,.urlset/master.m3u8?Expires=1637862092&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9hMDM4MGJhZWUyOWU0MTAxNzdiZDliNGYxY2Q0ZmZiNy9hc3NldHMvZmUxNTc3MzczNTllZDA1N2JiZDhhY2E0Mzg4MDRlNGVfLDQwNDgxMDMubXA0LDQwNDgxMDQubXA0LDQwNDgxMDIubXA0LDQwNDgxMDAubXA0LDQwNDgxMDEubXA0LDQwNDgwOTkubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Mzc4NjIwOTJ9fX1dfQ__&Signature=PgJXVfl3jy84KdUCLTb0jHRbleSPxjYNT7JZ8UgMdkZe4XnSO0O0S8wbjNGdD2tiJ2kisqts0hxqWEo70eWGJ2k8qQ0~xXEH-EWsllCoDlRjDEswKI9FzAx6mrV8jSxs2XXOElCRoOI2Txx7Zpi0Oyfbj3TuImiq2tGzBLw0wKc4l2LIwkdhDMGsQu1Jgk1Nr~Wc8rLGSN7~FIhooqp5bFLKXZ0b7KYyBJ-i2~www4wolCsRQnxEM65UjBYkVdAPSUY6zxLUt7BUIop0eUbiEzlhZz3Lst1yplmS~OeBoxo1GTH60-p8~yxSacngZEOvocAP-Su6ksWUqGuqM1VobQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/eng/-)
[ERROR] Found variable '${height}' in fileName but no values was internally found!
[INFO] Downloading skipped!
[INFO] Subtitle downloaded: [CR] The Hidden Dungeon Only I Can Enter (English Dub) - 11 [${height}p].01 eng English.ass
[INFO] Skip muxing since no vids are downloaded
/Users/USER/Apps/Animie/anidl/multi-downloader-nx/lib/modules/module.downloadArchive.js:116
    (_b = (kind.service == 'crunchy' ? data[kind.service][kind.type] : data[kind.service][kind.type]).find(function (a) { return a.id === ID; })) === null || _b === void 0 ? void 0 : (_a = _b.already).push.apply(_a, __spreadArray([], __read(episode), false));
                                                         ^

TypeError: Cannot read properties of undefined (reading 's')
    at downloaded (/Users/USER/Apps/Animie/anidl/multi-downloader-nx/lib/modules/module.downloadArchive.js:116:58)
    at /Users/USER/Apps/Animie/anidl/multi-downloader-nx/lib/crunchy.js:1097:65
    at step (/Users/USER/Apps/Animie/anidl/multi-downloader-nx/lib/crunchy.js:63:23)
    at Object.next (/Users/USER/Apps/Animie/anidl/multi-downloader-nx/lib/crunchy.js:44:53)
    at fulfilled (/Users/USER/Apps/Animie/anidl/multi-downloader-nx/lib/crunchy.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
```
<img width="1098" alt="Screen Shot 2021-11-24 at 4 43 44 am" src="https://user-images.githubusercontent.com/2242880/143077315-79aa98d4-92ca-43bf-ae62-d16aeddc17b3.png">

**Comment by izu-co** [comment]
Same command as before? Which version are you on now, btw?

If you are using an auto-updated build, can you quickly try if the error happens in a non-auto updated version?

**Comment by XxUnkn0wnxX** [comment]
I was using Ver: === Multi Downloader NX 2.0.2 === Commit: 0d051ac94ddbf9367ac25716ccc3d7bb5cfb1a16

On === Multi Downloader NX 2.0.1 === Commit: 162e8656b6bbaa92182046c2310f13f339c25d41
I only get `[ERROR] Found variable '${height}' in fileName but no values was internally found!` error

**Comment by izu-co** [comment]
Alright, thanks, looking into it.

The second one is correct btw since you do not download a stream, no quality has been selected.

**Comment by izu-co** [comment]
Fixed :)

**Comment by XxUnkn0wnxX** [comment]
yep all good..

howver i did run into a tsc issue earlier when jumping between versions...

```text
> ts-node tsc.ts

Error: ENOTEMPTY: directory not empty, rmdir 'lib/node_modules'
    at Object.rmdirSync (node:fs:1167:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1214:10)
    at removeSync (/Users/USER/Apps/Animie/anidl/multi-downloader-nx/node_modules/fs-extra/lib/remove/index.js:15:28)
    at /Users/USER/Apps/Animie/anidl/multi-downloader-nx/tsc.ts:21:13 {
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'lib/node_modules'
}
```

its not triggering anymore..  I think when I went from Commit: 0d051ac to an older one it triggered
