### ISSUE TITLE
[BUG] [Funimation] Invalid language tag passed to MKVMerge

### ISSUE THREAD

**Issue by Jaynator495** [anidl/multi-downloader-nx#192]
** Main info: **
For this series (or maybe due to my options?) It is only passing a single letter as the audio language to mkvmerge

Script version: 2.0.11
Service: Funimation
Show ID: 1311428 
Episode ID: ?
Command used: node .\index.js --service funi -s 1311428 --all --dubLang jpn eng --dlsubs all

Console output: 
```text
=== Multi Downloader NX 2.0.11 ===

[#1311428] Mushoku Tensei: Jobless Reincarnation (2021)
[0001] Mushoku Tensei: Jobless Reincarnation - #01 Jobless Reincarnation (00:23:40) [HD1080, Japanese, English] (selected)
[0002] Mushoku Tensei: Jobless Reincarnation - #02 Master (00:23:40) [HD1080, Japanese, English] (selected)
[0003] Mushoku Tensei: Jobless Reincarnation - #03 A Friend (00:23:40) [HD1080, Japanese, English] (selected)
[0004] Mushoku Tensei: Jobless Reincarnation - #04 Emergency Family Meeting (00:23:40) [HD1080, Japanese, English] (selected)
[0005] Mushoku Tensei: Jobless Reincarnation - #05 A Young Lady and Violence (00:23:40) [HD1080, Japanese, English] (selected)
[0006] Mushoku Tensei: Jobless Reincarnation - #06 A Day Off in Roa (00:23:40) [HD1080, Japanese, 
English] (selected)
[0007] Mushoku Tensei: Jobless Reincarnation - #07 What Lies Beyond Effort (00:23:40) [HD1080, Japanese, English] (selected)
[0008] Mushoku Tensei: Jobless Reincarnation - #08 Turning Point 1 (00:23:40) [HD1080, Japanese, English] (selected)
[0009] Mushoku Tensei: Jobless Reincarnation - #09 A Chance Encounter (00:23:40) [HD1080, Japanese, English] (selected)
[0010] Mushoku Tensei: Jobless Reincarnation - #10 The Value of a Life and the First Job (00:23:40) [HD1080, Japanese, English] (selected)
[0011] Mushoku Tensei: Jobless Reincarnation - #11 Children and Warriors (00:23:40) [HD1080, Japanese, English] (selected)
[0012] Mushoku Tensei: Jobless Reincarnation - #12 The Woman with the Demon Eyes (00:23:40) [HD1080, Japanese, English] (selected)
[0013] Mushoku Tensei: Jobless Reincarnation S2 - #13 Missed Connections (00:23:40) [HD1080, Japanese, English] (selected)
[0014] Mushoku Tensei: Jobless Reincarnation S2 - #14 No Such Thing As a Free Lunch (00:23:40) [HD1080, Japanese, English] (selected)
[0015] Mushoku Tensei: Jobless Reincarnation S2 - #15 Slow Life in the Doldia Village (00:23:40) [HD1080, Japanese, English] (selected)
[0016] Mushoku Tensei: Jobless Reincarnation S2 - #16 Family Squabble (00:23:39) [HD1080, Japanese, English] (selected)
[0017] Mushoku Tensei: Jobless Reincarnation S2 - #17 Reunion (00:23:40) [HD1080, Japanese, English] (selected)
[0018] Mushoku Tensei: Jobless Reincarnation S2 - #18 Separate Journeys (00:23:40) [HD1080, Japanese] (selected)
[0019] Mushoku Tensei: Jobless Reincarnation S2 - #19 Route Selection (00:23:40) [HD1080, Japanese] (selected)
[0020] Mushoku Tensei: Jobless Reincarnation S2 - #20 The Birth of My Little Sister, the Maid (00:23:40) [HD1080, Japanese] (selected)
[0021] Mushoku Tensei: Jobless Reincarnation S2 - #21 Turning Point 2 (00:23:40) [HD1080, Japanese] (selected)
[0022] Mushoku Tensei: Jobless Reincarnation S2 - #22 Dreams and Reality (00:23:40) [HD1080, Japanese] (selected)
[0023] Mushoku Tensei: Jobless Reincarnation S2 - #23 Wake Up and Take a Step (00:23:40) [HD1080, 
Japanese] (selected)

[INFO] Selected Episodes: 0001, 0002, 0003, 0004, 0005, 0006, 0007, 0008, 0009, 0010, 0011, 0012, 
0013, 0014, 0015, 0016, 0017, 0018, 0019, 0020, 0021, 0022, 0023

[INFO] Mushoku Tensei: Jobless Reincarnation - S1E1 - Jobless Reincarnation
[INFO] Available streams (Non-Encrypted):
[#1376136] English [Simulcast] (selected) (using 'English' for subtitles)
[#1321634] Japanese [Simulcast] (selected) (using 'English', 'Spanish', 'Portuguese' for subtitles)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:    
         1: 416x234 (532KiB/s) 
         2: 480x270 (780KiB/s) 
         3: 640x360 (1027KiB/s)
         4: 640x360 (1761KiB/s)
         5: 960x540 (2442KiB/s)
         6: 1280x720 (3014KiB/s)
         7: 1280x720 (4420KiB/s)
         8: 1440x810 (6138KiB/s)
         9: 1920x1080 (7946KiB/s)
        10: 1920x1080 (9784KiB/s)
[INFO] Selected layer: 10 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2315884/English/2315884_English_7747997_cc405dc7-7c40-eb11-8383-020165574d09_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMzE1ODg0L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzOTk0NTUwOH19fV19&Signature=OZkwXj5vJFhse-zYxDrhT9tVQHUVv6hTzESo8zHzCIcPay3XgnYCAzNDbPFMu4DWuAmPXSojB23GdOvOpJxucpkGaYmgAtJfKsN1OnmTBRsZZyp1KgNyu6fIc01PV6kQNBVbuwNx1NwtnXExqU78~tSCnXpLfgyEtZTRGepilWSFC9QWdRvrFgVYh0MWFyZOsrlTtT4kE9HSrKWbj5zB4upqmXWyexK-5fgsnmtCS7yCvPnFQhwEuOzjoGs~sItLUwfeVmJRRd-~lIuFdSv-zgEmHRb2lWcxCbpiDwz97Dw7Jk75o3Dn4sS~WOzQjtoUE2MPQqfIaAXuDmu1JevoPA__&rt=1427003
[INFO] Output filename: [Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].ts    
[INFO] Saving stream to «C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].video.e.ts»...
[INFO] 10 of 179 parts downloaded [6%] (26s | 45Mb/s)
[INFO] 20 of 179 parts downloaded [11%] (24s | 49Mb/s)
[INFO] 30 of 179 parts downloaded [17%] (23s | 49Mb/s)
[INFO] 40 of 179 parts downloaded [22%] (23s | 47Mb/s)
[INFO] 50 of 179 parts downloaded [28%] (23s | 45Mb/s)
[INFO] 60 of 179 parts downloaded [34%] (20s | 47Mb/s)
[INFO] 70 of 179 parts downloaded [39%] (18s | 49Mb/s)
[INFO] 80 of 179 parts downloaded [45%] (16s | 49Mb/s)
[INFO] 90 of 179 parts downloaded [50%] (14s | 50Mb/s)
[INFO] 100 of 179 parts downloaded [56%] (13s | 50Mb/s)
[INFO] 110 of 179 parts downloaded [61%] (11s | 51Mb/s)
[INFO] 120 of 179 parts downloaded [67%] (9s | 52Mb/s)
[INFO] 130 of 179 parts downloaded [73%] (8s | 52Mb/s)
[INFO] 140 of 179 parts downloaded [78%] (6s | 53Mb/s)
[INFO] 150 of 179 parts downloaded [84%] (4s | 53Mb/s)
[INFO] 160 of 179 parts downloaded [89%] (3s | 53Mb/s)
[INFO] 170 of 179 parts downloaded [95%] (1s | 53Mb/s)
[INFO] 179 of 179 parts downloaded [100%] (0s | 53Mb/s)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (531KiB/s)
         2: 480x270 (779KiB/s)
         3: 640x360 (1023KiB/s)
         4: 640x360 (1753KiB/s)
         5: 960x540 (2429KiB/s)
         6: 1280x720 (3004KiB/s)
         7: 1280x720 (4357KiB/s)
         8: 1440x810 (6097KiB/s)
         9: 1920x1080 (7924KiB/s)
        10: 1920x1080 (9697KiB/s)
[INFO] Selected layer: 10 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2315884/Japanese/2315884_Japanese_7658062_cc405dc7-7c40-eb11-8383-020165574d09_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMzE1ODg0L0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Mzk5NDU1MDl9fX1dfQ__&Signature=ZC8HSXYwQ30i~lYnp7RwQ2-A3gn7WABoeITyPRywgE4zl4y45FZuUwVCLgxb6A3k8D~Gxi8V4maf~XY7Py2D3go2oUTyVXycPLZSQLOpc9DXwQjc7EHuLwN2bMhBkb~IVF0z9GmwqwGDtdJUicpAsUz1eRqcR3IdyfFW18WdqNblWwT0Rlwni~VJ9LYGG3AGamURz75J5NxLA0n7mr7nMYcPledIngHWJuHM0pLaL8FbV3fWZBrHEIDxo8C5U8etOYuH2ikmtj~aMy4I~yG5gnjXra6Ues8Lgoeu-gbxdbwHqaK5yxAQORQozyAVCZdYcvmHhJdiNHkQy3LQ~gafRw__&rt=1427003
[INFO] Output filename: [Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].ts    
[INFO] Saving stream to «C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].video.j.ts»...
[INFO] 10 of 179 parts downloaded [6%] (28s | 44Mb/s)
[INFO] 20 of 179 parts downloaded [11%] (26s | 44Mb/s)
[INFO] 30 of 179 parts downloaded [17%] (25s | 46Mb/s)
[INFO] 40 of 179 parts downloaded [22%] (23s | 47Mb/s)
[INFO] 50 of 179 parts downloaded [28%] (22s | 47Mb/s)
[INFO] 60 of 179 parts downloaded [34%] (19s | 49Mb/s)
[INFO] 70 of 179 parts downloaded [39%] (18s | 49Mb/s)
[INFO] 80 of 179 parts downloaded [45%] (16s | 50Mb/s)
[INFO] 90 of 179 parts downloaded [50%] (14s | 50Mb/s)
[INFO] 100 of 179 parts downloaded [56%] (13s | 49Mb/s)
[INFO] 110 of 179 parts downloaded [61%] (11s | 49Mb/s)
[INFO] 120 of 179 parts downloaded [67%] (10s | 49Mb/s)
[INFO] 130 of 179 parts downloaded [73%] (8s | 49Mb/s)
[INFO] 140 of 179 parts downloaded [78%] (7s | 48Mb/s)
[INFO] 150 of 179 parts downloaded [84%] (5s | 48Mb/s)
[INFO] 160 of 179 parts downloaded [89%] (3s | 48Mb/s)
[INFO] 170 of 179 parts downloaded [95%] (2s | 48Mb/s)
[INFO] 179 of 179 parts downloaded [100%] (0s | 48Mb/s)
[INFO] Downloading subtitles...
[INFO] Subtitles downloaded!

> "mkvmerge" -o "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"undefined [Uncut]" --track-name 1:"undefined [Uncut]" --language 1:e "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].video.e.ts" --no-video --audio-tracks 1 --track-name 1:"undefined [Uncut]" --language 1:j "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].video.j.ts" --track-name 0:"English" --language 0:"eng" "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].subtitle.eng.ass" --track-name 0:"Spanish" --language 0:"spa" "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].subtitle.spa.ass" --track-name 0:"Portuguese" --language 0:"por" "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].subtitle.por.ass" --no-attachments   
mkvmerge v60.0.0 ('Are We Copies?') 64-bit
Error: 'e' is not a valid IETF BCP 47/RFC 5646 language tag in '--language 1:e'. Additional information from the parser: The value does not adhere to the general structure of IETF BCP 47/RFC 5646 
language tags.
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: "C:\mkvtoolnix\mkvmerge.exe" -o "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].mkv" --no-date 
--disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"undefined [Uncut]" --track-name 1:"undefined [Uncut]" --language 1:e "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].video.e.ts" --no-video --audio-tracks 1 --track-name 1:"undefined [Uncut]" --language 1:j "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].video.j.ts" --track-name 0:"English" --language 0:"eng" "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - 
S01E01 [1080p].subtitle.eng.ass" --track-name 0:"Spanish" --language 0:"spa" "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].subtitle.spa.ass" --track-name 0:"Portuguese" --language 0:"por" "C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - S01E01 [1080p].subtitle.por.ass" --no-attachments
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exec (C:\_FILES_\_MEDIA_\multi-downloader-nx-master\node_modules\sei-helper\src\main.js:174:30)
    at C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\funi.js:976:30
    at step (C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\funi.js:63:23)
    at Object.next (C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\funi.js:44:53)
    at fulfilled (C:\_FILES_\_MEDIA_\multi-downloader-nx-master\lib\funi.js:35:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 14780,
  stdout: null,
  stderr: null
}
```

** Additional Info: **

**Comment by izu-co** [comment]
Fixed in the newest commit.
