### ISSUE TITLE
[BUG] [Funimation] Remux error

### ISSUE THREAD

**Issue by Jaynator495** [anidl/multi-downloader-nx#201]
### Program version

2.0.14

### Service

Funimation

### Command used

node .\index.js --service funi -s 20224 --all --dubLang jpn eng --dlsubs all

### Show ID

20224

### Episode

642

### Console Output

```text
[INFO] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!
[INFO] Available streams (Non-Encrypted):
[#52112] Japanese [Simulcast]
[#1337894] English [Uncut] (selected) (using 'English' for subtitles)
[#1337895] Japanese [Uncut] (selected) (using 'English' for subtitles)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (474KiB/s)
         2: 640x360 (705KiB/s)
         3: 768x432 (1096KiB/s)
         4: 768x432 (1466KiB/s)
         5: 960x540 (2361KiB/s)
         6: 1280x720 (3367KiB/s)
         7: 1280x720 (4953KiB/s)
         8: 1920x1080 (6947KiB/s)
         9: 1920x1080 (9119KiB/s)
[INFO] Selected layer: 9 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2141797/21eb9fc7-0688-4339-80bc-5ad8df6241f2strnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MTc5Ny8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQwMjUxNjE1fX19XX0_&Signature=vJ4UA8JxfptfTjjt3Xr1OfebTbUqx7NK88~tuuRE0rWSPHLYarpgtHdqlaYEe9QAnPHhIhcks3ptGpAjoayHY5rOjwGu3LnBfMMdVC4wc85hYa-e84tFpe4i6bMRyFhcqMwHLsR69P9P2I2staIUw48HzYRKTpFBsSNuKKiBNbph1L90O~BbeOaACG-NdNqPfPCWX6Di9GARVzOb9jo7m4yiXPT-a-N6NpKYlKXzE5oyTTHdOUj8hAGJR-ZFvmsqiZnAEyIfE7RyUe1DUup3xcddN4REMjJF2wjGYEPmxV9DkKEqhSYqbpSdhmtOkukk~e~7ME8CxX6A8JoREEsjdw__&rt=1431363
[INFO] Output filename: [Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.ts
[INFO] Saving stream to «D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.ts»...
[INFO] 20 of 723 parts downloaded [3%] (32s | 36Mb/s)
[INFO] 40 of 723 parts downloaded [6%] (37s | 29Mb/s)
[INFO] 60 of 723 parts downloaded [8%] (34s | 30Mb/s)
[INFO] 80 of 723 parts downloaded [11%] (35s | 28Mb/s)
[INFO] 100 of 723 parts downloaded [14%] (31s | 31Mb/s)
[INFO] 120 of 723 parts downloaded [17%] (31s | 30Mb/s)
[INFO] 140 of 723 parts downloaded [19%] (29s | 31Mb/s)
[INFO] 160 of 723 parts downloaded [22%] (28s | 31Mb/s)
[INFO] 180 of 723 parts downloaded [25%] (25s | 33Mb/s)
[INFO] 200 of 723 parts downloaded [28%] (24s | 33Mb/s)
[INFO] 220 of 723 parts downloaded [30%] (22s | 34Mb/s)
[INFO] 240 of 723 parts downloaded [33%] (22s | 34Mb/s)
[INFO] 260 of 723 parts downloaded [36%] (21s | 34Mb/s)
[INFO] 280 of 723 parts downloaded [39%] (21s | 33Mb/s)
[INFO] 300 of 723 parts downloaded [41%] (20s | 33Mb/s)
[INFO] 320 of 723 parts downloaded [44%] (19s | 33Mb/s)
[INFO] 340 of 723 parts downloaded [47%] (18s | 33Mb/s)
[INFO] 360 of 723 parts downloaded [50%] (16s | 34Mb/s)
[INFO] 380 of 723 parts downloaded [53%] (15s | 34Mb/s)
[INFO] 400 of 723 parts downloaded [55%] (14s | 34Mb/s)
[INFO] 420 of 723 parts downloaded [58%] (13s | 34Mb/s)
[INFO] 440 of 723 parts downloaded [61%] (13s | 33Mb/s)
[INFO] 460 of 723 parts downloaded [64%] (12s | 33Mb/s)
[INFO] 480 of 723 parts downloaded [66%] (11s | 34Mb/s)
[INFO] 500 of 723 parts downloaded [69%] (10s | 33Mb/s)
[INFO] 520 of 723 parts downloaded [72%] (9s | 34Mb/s)
[INFO] 540 of 723 parts downloaded [75%] (8s | 34Mb/s)
[INFO] 560 of 723 parts downloaded [77%] (7s | 34Mb/s)
[INFO] 580 of 723 parts downloaded [80%] (6s | 34Mb/s)
[INFO] 600 of 723 parts downloaded [83%] (6s | 34Mb/s)
[INFO] 620 of 723 parts downloaded [86%] (5s | 34Mb/s)
[INFO] 640 of 723 parts downloaded [89%] (4s | 34Mb/s)
[INFO] 660 of 723 parts downloaded [91%] (3s | 34Mb/s)
[INFO] 680 of 723 parts downloaded [94%] (2s | 34Mb/s)
[INFO] 700 of 723 parts downloaded [97%] (1s | 34Mb/s)
[INFO] 720 of 723 parts downloaded [99%] (0s | 34Mb/s)
[INFO] 723 of 723 parts downloaded [100%] (0s | 34Mb/s)
[INFO] Saving stream to «D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.audio.eng.ts»...
[INFO] 20 of 725 parts downloaded [3%] (13s | 3.4Mb/s)
[INFO] 40 of 725 parts downloaded [6%] (14s | 3.2Mb/s)
[INFO] 60 of 725 parts downloaded [8%] (10s | 4.2Mb/s)
[INFO] 80 of 725 parts downloaded [11%] (10s | 4.4Mb/s)
[INFO] 100 of 725 parts downloaded [14%] (10s | 4.2Mb/s)
[INFO] 120 of 725 parts downloaded [17%] (9s | 4.3Mb/s)
[INFO] 140 of 725 parts downloaded [19%] (9s | 4.2Mb/s)
[INFO] 160 of 725 parts downloaded [22%] (8s | 4.4Mb/s)
[INFO] 180 of 725 parts downloaded [25%] (8s | 4.4Mb/s)
[INFO] 200 of 725 parts downloaded [28%] (8s | 4.5Mb/s)
[INFO] 220 of 725 parts downloaded [30%] (7s | 4.7Mb/s)
[INFO] 240 of 725 parts downloaded [33%] (6s | 4.9Mb/s)
[INFO] 260 of 725 parts downloaded [36%] (6s | 5.0Mb/s)
[INFO] 280 of 725 parts downloaded [39%] (6s | 5.2Mb/s)
[INFO] 300 of 725 parts downloaded [41%] (5s | 5.4Mb/s)
[INFO] 320 of 725 parts downloaded [44%] (5s | 5.5Mb/s)
[INFO] 340 of 725 parts downloaded [47%] (4s | 5.6Mb/s)
[INFO] 360 of 725 parts downloaded [50%] (4s | 5.5Mb/s)
[INFO] 380 of 725 parts downloaded [52%] (6s | 3.8Mb/s)
[INFO] 400 of 725 parts downloaded [55%] (6s | 3.8Mb/s)
[INFO] 420 of 725 parts downloaded [58%] (5s | 3.7Mb/s)
[INFO] 440 of 725 parts downloaded [61%] (5s | 3.7Mb/s)
[INFO] 460 of 725 parts downloaded [63%] (6s | 2.8Mb/s)
[INFO] 480 of 725 parts downloaded [66%] (6s | 2.9Mb/s)
[INFO] 500 of 725 parts downloaded [69%] (5s | 2.8Mb/s)
[INFO] 520 of 725 parts downloaded [72%] (5s | 2.8Mb/s)
[INFO] 540 of 725 parts downloaded [74%] (5s | 2.2Mb/s)
[INFO] 560 of 725 parts downloaded [77%] (5s | 2.3Mb/s)
[INFO] 580 of 725 parts downloaded [80%] (4s | 2.3Mb/s)
[INFO] 600 of 725 parts downloaded [83%] (3s | 2.4Mb/s)
[INFO] 620 of 725 parts downloaded [86%] (3s | 2.4Mb/s)
[INFO] 640 of 725 parts downloaded [88%] (2s | 2.5Mb/s)
[INFO] 660 of 725 parts downloaded [91%] (2s | 2.6Mb/s)
[INFO] 680 of 725 parts downloaded [94%] (1s | 2.6Mb/s)
[INFO] 700 of 725 parts downloaded [97%] (1s | 2.6Mb/s)
[INFO] 720 of 725 parts downloaded [99%] (0s | 2.7Mb/s)
[INFO] 725 of 725 parts downloaded [100%] (0s | 2.7Mb/s)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (542KiB/s)
         2: 480x270 (778KiB/s)
         3: 640x360 (1010KiB/s)
         4: 640x360 (1708KiB/s)
         5: 960x540 (2361KiB/s)
         6: 1280x720 (2962KiB/s)
         7: 1280x720 (4253KiB/s)
         8: 1440x810 (5975KiB/s)
         9: 1920x1080 (7755KiB/s)
        10: 1920x1080 (9595KiB/s)
[INFO] Selected layer: 10 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2326494/Japanese/2326494_Japanese_7673876_7b223a6d-6d57-eb11-8383-020165574d09_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMzI2NDk0L0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAyNTE2MTZ9fX1dfQ__&Signature=KJ4qr8tbgNzsDg7pF16A8XHnO6Kms~aQsxh3xGuLqh2VK33FGno8bnw-d7yU8auwsOvpNM8pW6kwSAkeeBCsvXhzqZk0AAleMyeh~DX4IK6QOPYmqieJX~ffbAVFns2wpQG1vIhs5SGyC-u4JqmZ93fKbOBcBd6Xu8rLgomXowvxQrC5qFOPFlwQQPbKKYdeF-SvJoFOrNOCLchEGYvm4p0MuIogtDHTIIWhPRpKOWXEXkwNMez9YYCbT6w14wf8tRWbwjje3KQ3nbNicdXcKL5FzDRVIRdZY9uBRNK1mbpo8NZg43chRaHsten3dDEfXms1E5~B0lZ2yYEeCvoEzA__&rt=1448641
[INFO] Output filename: [Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.ts
[INFO] Saving stream to «D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.jpn.ts»...
[INFO] 20 of 181 parts downloaded [11%] (29s | 47Mb/s)
[INFO] 40 of 181 parts downloaded [22%] (25s | 46Mb/s)
[INFO] 60 of 181 parts downloaded [33%] (21s | 47Mb/s)
[INFO] 80 of 181 parts downloaded [44%] (17s | 48Mb/s)
[INFO] 100 of 181 parts downloaded [55%] (14s | 49Mb/s)
[INFO] 120 of 181 parts downloaded [66%] (10s | 49Mb/s)
[INFO] 140 of 181 parts downloaded [77%] (7s | 49Mb/s)
[INFO] 160 of 181 parts downloaded [88%] (4s | 49Mb/s)
[INFO] 180 of 181 parts downloaded [99%] (0s | 47Mb/s)
[INFO] 181 of 181 parts downloaded [100%] (0s | 46Mb/s)
[INFO] Downloading subtitles...
[INFO] Subtitles downloaded!

> "mkvmerge" -o "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --no-audio --track-name 0:"English [Uncut]" --language 0:eng "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.ts" --no-video --audio-tracks 1 --track-name 1:"Japanese [Uncut]" --language 1:jpn "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.jpn.ts" --track-name 0:"English" --language 0:eng --no-video --audio-tracks 0 "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.audio.eng.ts" --track-name 0:"English CC" --language 0:"eng" "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.cc.ass" --track-name 0:"English" --language 0:"eng" "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.ass" --no-attachments
mkvmerge v60.0.0 ('Are We Copies?') 64-bit
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.jpn.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.audio.eng.ts': Using the demultiplexer for the format 'AAC'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.cc.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
Warning: 'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.ass' track 0: SSA/ASS: The following line will be skipped as one of the timestamps is less than 0, or the end timestamp is less than the start timestamp: Dialogue: 0,0:20:37.17,0:20:37.03,Main,,0,0,0,,Captain, look at this!
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.jpn.ts' track 1: Using the output module for the format 'AAC'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.audio.eng.ts' track 0: Using the output module for the format 'AAC'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.cc.ass' track 0: Using the output module for the format 'text subtitles'.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.ass' track 0: Using the output module for the format 'text subtitles'.
The file 'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.mkv' has been opened for writing.
'D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 10 seconds.
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: "C:\mkvtoolnix\mkvmerge.exe" -o "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --no-audio --track-name 0:"English [Uncut]" --language 0:eng "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.ts" --no-video --audio-tracks 1 --track-name 1:"Japanese [Uncut]" --language 1:jpn "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.video.jpn.ts" --track-name 0:"English" --language 0:eng --no-video --audio-tracks 0 "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.audio.eng.ts" --track-name 0:"English CC" --language 0:"eng" "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.cc.ass" --track-name 0:"English" --language 0:"eng" "D:\_MEDIA_\op\multi-downloader-nx-master\lib\videos\[Funimation] [1080p] One Piece - S11E642 - The Stratagem of the Century! Doflamingo Makes His Move!.subtitle.eng.ass" --no-attachments
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exec (D:\_MEDIA_\op\multi-downloader-nx-master\node_modules\sei-helper\src\main.js:174:30)
    at D:\_MEDIA_\op\multi-downloader-nx-master\lib\funi.js:980:30
    at step (D:\_MEDIA_\op\multi-downloader-nx-master\lib\funi.js:52:23)
    at Object.next (D:\_MEDIA_\op\multi-downloader-nx-master\lib\funi.js:33:53)
    at fulfilled (D:\_MEDIA_\op\multi-downloader-nx-master\lib\funi.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 37668,
  stdout: null,
  stderr: null
}
```

### Additional Information

```shell
It appears that episode 642 of One Piece fails to remux, but I'm not seeing an error actually spitting out and the MKV does appear to be created, though for some reason it appears to have extra subtitle tracks. I tried getting rid of the output into another folder and trying to download 642 by itself, but it results in the same error.
```

**Comment by izu-co** [comment]
The problem is that the one line in the English subtitle is wrong. I would bet it is because of funimation.
Since mkvmerge prints an error exit code, one is used with internally terminates the program.

**Comment by izu-co** [comment]
The fix may take a bit tho since the problem lives in `sei-helper` and I have currently no access to it.

**Comment by starm7md** [comment]
![image](https://user-images.githubusercontent.com/65809932/148722437-1f527deb-2f37-4c7f-9edb-b45692080eec.png)
![image](https://user-images.githubusercontent.com/65809932/148722453-2e4b0e81-3909-4bd8-a3d9-38fc568284f5.png)
![image](https://user-images.githubusercontent.com/65809932/148722473-1ed10828-1bce-4213-9cde-026bf863ddf6.png)

can anyone tell me why MKVMerge is not working please

**Comment by izu-co** [comment]
As an update: I am currently hard at work with the gui. Once that is done i will steal the method and reimplement it since @anidl-git is currently not responding to my messanges
