### ISSUE TITLE
[ERROR] YAMLSyntaxError: Invalid escape sequence

### ISSUE THREAD

**Issue by Aislynne** [anidl/multi-downloader-nx#231]
```
@ C:\Users\USER\Downloads\multi-downloader-nx-2.0.18-win64

> anidl.exe --service funi --auth
[INFO] Token not set!


=== Multi Downloader NX 2.0.18 ===

[ERROR] YAMLSyntaxError: Invalid escape sequence \Users\USER
    at QuoteDouble.parseCharCode (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\parse-cst.js:1361:19)
    at QuoteDouble.get strValue [as strValue] (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\parse-cst.js:1316:25)
    at Object.resolveString [as resolve] (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1328:20)
    at resolveByTagName (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1430:25)
    at resolveTag (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1460:17)
    at resolveNodeValue (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1581:23)
    at resolveNode (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1629:15)
    at resolveBlockMapItems (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1823:38)
    at Object.resolveMap [as resolve] (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1658:79)
    at resolveByTagName (C:\snapshot\multi-downloader-nx\node_modules\yaml\dist\resolveSeq-d03cb037.js:1430:25) {
  source: QuoteDouble {
    error: null,
    range: Range { start: 8, end: 76 },
    valueRange: Range { start: 8, end: 76 },
    props: [],
    type: 'QUOTE_DOUBLE',
    value: null,
    resolved: Scalar {
      value: 'C:\\Users\\USER\\Downloads\ffmpeg-4.4.1-full_build\bin\ffmpeg.exe',
      range: [Array],
      type: 'QUOTE_DOUBLE'
    }
  }
}
[Q] LOGIN/EMAIL: USER@EMAIL.COM
[Q] PASSWORD   : PW1234!
[ERROR] RequestError: ENOTFOUND`
```
What step did I miss? Does the token auto setup after initial use?

**Comment by izu-co** [comment]
The `bin-path.yml` file is wrong. Please set the FFmpeg value like so: `"PATH"`.

**Comment by Aislynne** [comment]
I have it working now. But how do I select the episodes I want to download? I am trying to download all of One Piece dub.

```
anidl.exe --service funi -s 20224 -q 10 --nosubs -e 0001-1007
[ **It lists out over 1000 episodes**]
[INFO] Episodes not selected!`
```

**Comment by izu-co** [comment]
-e 1-1000
