### ISSUE TITLE
BUG - GUI Keeps Crashing on macos

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#258]
### Program version

3.0.0

### Service

Irrelevant

### Command used

N/A

### Show ID

N/A

### Episode

N/A

### Console Output

I either Get this:
```text
Uncaught Exception:
Error: EROFS: read-only file system, mkdir '/private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/AppTranslocation/F72DD097-7669-4E4D-BBFD-F7124782312B/d/multi-downloader-nx.app/Contents/Resources/app/gui/electron/src/logs'
at Object.mkdirSync (node:fs:1334:3)
at /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/AppTranslocation/F72DD097-7669-4E4D-BBFD-F7124782312B/d/multi-downloader-nx.app/Contents/Resources/app/gui/electron/src/index.js:64:26
at Object.<anonymous> (/private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/AppTranslocation/F72DD097-7669-4E4D-BBFD-F7124782312B/d/multi-downloader-nx.app/Contents/Resources/app/gui/electron/src/index.js:66:7)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Object.<anonymous> (node:electron/js2c/browser_init:193:3197)
at Object../lib/browser/init.ts (node:electron/js2c/browser_init:193:3401)
```
![Screen Shot 2022-02-17 at 8 04 57 am](https://user-images.githubusercontent.com/2242880/154356918-a08b3870-bb78-426f-ad72-5b27246c52f5.jpg)

Or this when trying to run Gui via terminal.
```text
[77587:0217/080614.848633:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up com.electron.multi-downloader-nx.MachPortRendezvousServer.77578: Unknown service name (1102)
[77587:0217/080614.850825:ERROR:child_thread_impl.cc(226)] Mach rendezvous failed, terminating process (parent died?)
```

### Additional Information
[Video Of Crash](https://www.dropbox.com/s/hbor0qx51pxon54)
just watch as it crashes every time i open its like 1 seconds it opens & insta closes
not even sure where logs are for this.

**Comment by izu-co** [comment]
Since I have no Mac I couldn’t test it for make unfortunately- I will investigate the source later 

Thanks for the report

**Comment by izu-co** [comment]
On error i see right now is that the file system seems to be read only. This could be a permission error or an error with electron

**Comment by izu-co** [comment]
I can't build a 'test version' for you but can you try to build from source by running `npm run build-macos-gui`

**Comment by XxUnkn0wnxX** [comment]
well it built still getting
```text
[248:0218/213823.584547:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up com.electron.multi-downloader-nx.MachPortRendezvousServer.1: Unknown service name (1102)
[248:0218/213823.586852:ERROR:child_thread_impl.cc(226)] Mach rendezvous failed, terminating process (parent died?
```

same thing like in the video demo where it opens & closes in under a second.

**Comment by izu-co** [comment]
Can you try to build and then running `npx electron-forge start` in the lib folder? Maybe I can get more information there, because I have currently no idea what the problem could be.

**Comment by XxUnkn0wnxX** [comment]
nope still crashing
![Screen Shot 2022-02-20 at 4 28 00 am](https://user-images.githubusercontent.com/2242880/154812058-b9ba0083-f5bc-4db8-b58d-5c4277abadbd.jpg)

Video
https://user-images.githubusercontent.com/2242880/154812066-d026e7ec-2473-4893-9901-5852f39aef92.mp4

**Comment by izu-co** [comment]
Do you know if other electron apps work on your machine? You can try by running `npx create-electron-app@latest my-app` and them `npm run start` in the directory. 

I think that this will work. The problem is I can't even find something online about the error you are facing, and I have no clue why it should only crash on mac...

**Comment by izu-co** [comment]
I got out my old Mac and found the issue for the crash. Apparently the response from the popup is `-1` and the app is closed by my code. Why its `-1` tho no idea.

I make a new release with all the builds shortly
