### ISSUE TITLE
[GUI] BUG "Content directory not accessible!"

### ISSUE THREAD

**Issue by FaceHiddenInsideTheDark** [anidl/multi-downloader-nx#270]
### Program version

3.0.1

### Service

Both

### Command used

[GUI]

### Show ID

4036736

### Episode

7

### Console Output
```
[INFO] Popup response: 1
C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\gui\electron\build
Express started
[ERROR] Content directory not accessible!
[INFO] Token not set!

[#4036736] The Genius Prince's Guide to Raising a Nation Out of Debt (2022)
[INFO] Authentication success, your token: ba3571f8********************************

[ERROR] Can't save token file to disk!
[#4036736] The Genius Prince's Guide to Raising a Nation Out of Debt (2022)
[0001] The Genius Prince's Guide to Raising a Nation Out of Debt - #01 The Prince Who Would Sell His Kingdom (00:23:41) [HD1080, Japanese]
[0002] The Genius Prince's Guide to Raising a Nation Out of Debt - #02 Wein Salema Arbalest, Battlefield Tactician (00:23:41) [HD1080, Japanese]
[0003] The Genius Prince's Guide to Raising a Nation Out of Debt - #03 A Proposal as a Pretext (00:23:40) [HD1080, Japanese]
[0004] The Genius Prince's Guide to Raising a Nation Out of Debt - #04 It Takes Two to Tango (00:23:40) [HD1080, Japanese]
[0005] The Genius Prince's Guide to Raising a Nation Out of Debt - #05 A Diabolical Scheme (00:23:40) [HD1080, Japanese]
[0006] The Genius Prince's Guide to Raising a Nation Out of Debt - #06 Holy Intrigue! (00:23:39) [HD1080, Japanese]
[0007] The Genius Prince's Guide to Raising a Nation Out of Debt - #07 Yesterday's Enemy Is Today's... (00:23:40) [HD1080, Japanese] (selected)

[#4036736] The Genius Prince's Guide to Raising a Nation Out of Debt (2022)
[0001] The Genius Prince's Guide to Raising a Nation Out of Debt - #01 The Prince Who Would Sell His Kingdom (00:23:41) [HD1080, Japanese]
[0002] The Genius Prince's Guide to Raising a Nation Out of Debt - #02 Wein Salema Arbalest, Battlefield Tactician (00:23:41) [HD1080, Japanese]
[0003] The Genius Prince's Guide to Raising a Nation Out of Debt - #03 A Proposal as a Pretext (00:23:40) [HD1080, Japanese]
[0004] The Genius Prince's Guide to Raising a Nation Out of Debt - #04 It Takes Two to Tango (00:23:40) [HD1080, Japanese]
[0005] The Genius Prince's Guide to Raising a Nation Out of Debt - #05 A Diabolical Scheme (00:23:40) [HD1080, Japanese]
[0006] The Genius Prince's Guide to Raising a Nation Out of Debt - #06 Holy Intrigue! (00:23:39) [HD1080, Japanese]
[0007] The Genius Prince's Guide to Raising a Nation Out of Debt - #07 Yesterday's Enemy Is Today's... (00:23:40) [HD1080, Japanese] (selected)

[INFO] Servers available:
	vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
	 1: 416x234 (459KiB/s)
	 2: 640x360 (718KiB/s)
	 3: 768x432 (1129KiB/s)
	 4: 768x432 (1539KiB/s)
	 5: 960x540 (2549KiB/s)
	 6: 1280x720 (3582KiB/s)
	 7: 1280x720 (5166KiB/s)
	 8: 1920x1080 (6840KiB/s)
	 9: 1920x1080 (8787KiB/s)
[INFO] Selected layer: 9 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2779825/0281b1fe-1819-43f5-8072-bbd825ba0958strnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?t=exp%3D1646086823%7Eacl%3Dhttps%3A%2F%2Fvideo.prd.funimation.com%2FFunimationStoreFront%2FV2779825%2F*%7Ehmac%3D1f0fda6f6488c39125ea5dbaa7abfc4a156f081696f970296ba2dc7de1080c06
[INFO] Output filename: [Funimation] The Genius Prince's Guide to Raising a Nation Out of Debt - S01E07 [1080p].ts
Error occurred in handler for 'downloadItem': Error: ENOTDIR, not a directory
    at createError (node:electron/js2c/asar_bundle:5:1336)
    at Object.e.mkdir (node:electron/js2c/asar_bundle:5:12368)
    at node:internal/util:363:7
    at new Promise (<anonymous>)
    at Object.mkdir (node:internal/util:349:12)
    at C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:874:84
    at step (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:63:23)
    at Object.next (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:44:53)
    at step (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:48:139)
    at Object.next (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:44:53) {
  code: 'ENOTDIR',
  errno: -20
}
```

### Additional Information

I am using the Windows build, with Windows 10 Enterprise LTSC.
It appears that %LocalAppData%\Programs\multi-downloader-nx\resources\app.asar is being treated as a directory?
Error occurs when downloading, or simply pressing the "Open Output Directory" gives me the following error:
"Windows cannot find 'C:\Users\W\Appdata\Local\Programs\multi-downloader-nx\resources\app.asar\videos'. Make sure you typed the name correctly, and then try again."

**Comment by izu-co** [comment]
Fixed with the newest commit and later in version `3.0.2` when it will release.

**Comment by izu-co** [comment]
The release is now released.
