### ISSUE TITLE
Error downloading episodes using GUI

### ISSUE THREAD

**Issue by BuckMisterFullerene** [anidl/multi-downloader-nx#283]
### Program version

3.0.4

### Operating System

MacOS

### Type

Gui

### Service

Crunchyroll

### Command used

[Item ID: GRGGPG93R] [Quality Level: 0] [Episode Select: 32] [Dub Languages: jpn] [Sub Languages: en] [Filename: 32]

### Show ID

GRGGPG93R

### Episode

32

### Console Output

**Download error
Unable to download episode 32 from GRGGPG93R**

Download error: Unable to download episode 32 from GRGGPG93R
at CrunchyHandler.<anonymous> (/Applications/multi-downloader-nx.app/Contents/Resources/app.asar/gui/electron/src/serviceHandler/crunchyroll.js:253:34)
at step (/Applications/multi-downloader-nx.app/Contents/Resources/app.asar/gui/electron/src/serviceHandler/crunchyroll.js:59:23)
at Object.next (/Applications/multi-downloader-nx.app/Contents/Resources/app.asar/gui/electron/src/serviceHandler/crunchyroll.js:40:53)
at fulfilled (/Applications/multi-downloader-nx.app/Contents/Resources/app.asar/gui/electron/src/serviceHandler/crunchyroll.js:31:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by izu-co** [comment]
Have you done anything special? And when did the bug happen (e.g. during muxing, downloading, etc.)?

**Comment by BuckMisterFullerene** [comment]
Hi! I haven't done anything special, and the bug occurred during download.

**Comment by izu-co** [comment]
I can't replicate, since no show with the given ID exists.
Feel free to reopen if you have the issue, and just stated the ID wrong

**Comment by BuckMisterFullerene** [comment]
Hmm, that's weird. That's the ID that shows up and is selected when I type "fullmetal alchemist" and select the first show that appears on the list.
