### ISSUE TITLE
Subtitle BUG

### ISSUE THREAD

**Issue by StrPlayer** [anidl/multi-downloader-nx#302]
### Program version

3.0.5/3.0.6

### Operating System

Windows

### Type

Gui

### Service

Crunchyroll

### Command used

N/A

### Show ID

GY5P48XEY

### Episode

34

### Console Output

Error occurred in handler for 'downloadItem': TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:166:54
    at step (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:33:23)
    at Object.next (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:14:53)
    at C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:4:12)
    at Object.loadBinCfg (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:146:39)
    at Crunchy.<anonymous> (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\crunchy.js:1814:54)
    at step (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\crunchy.js:67:23)
Appdata C:\Users\Star\AppData\Roaming

### Additional Information

```Text
The issue is not that the program cant find subtitles, It's that there are none you should add it so when no subtitle is found skip searching for it
```

**Comment by StrPlayer** [comment]
NVM not a sub issue not sure what issue it is, but it downloads everything fine but doesn't convert it

**Comment by StrPlayer** [comment]
Fixed after deleting all files in appdata and reinstalling
