### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by drknss89** [anidl/multi-downloader-nx#317]
### Program version

3.07

### Operating System

Windows

### Type

Gui

### Service

Both

### Command used

N/A

### Show ID

N/A

### Episode

N/A

### Console Output

TypeError: e.join is not a function

at http://localhost:3000/static/js/main.5626b1bf.js:2:291499
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:253186
at http://localhost:3000/static/js/main.5626b1bf.js:2:266059
at http://localhost:3000/static/js/main.5626b1bf.js:2:299145
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:272197
at div
at Vf (http://localhost:3000/static/js/main.5626b1bf.js:2:359209)
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:312098
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:312098
at Yf (http://localhost:3000/static/js/main.5626b1bf.js:2:363575)
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:312098
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:215326
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at n (http://localhost:3000/static/js/main.5626b1bf.js:2:205615)
at http://localhost:3000/static/js/main.5626b1bf.js:2:209714
at K (http://localhost:3000/static/js/main.5626b1bf.js:2:151607)
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:146406
at http://localhost:3000/static/js/main.5626b1bf.js:2:154773
at http://localhost:3000/static/js/main.5626b1bf.js:2:212917
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:218550
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:312098
at Ap (http://localhost:3000/static/js/main.5626b1bf.js:2:386526)
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:312098
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:312098
at Wp (http://localhost:3000/static/js/main.5626b1bf.js:2:387285)
at Bp
at Hp (http://localhost:3000/static/js/main.5626b1bf.js:2:387977)
at xc (http://localhost:3000/static/js/main.5626b1bf.js:2:307936)
at div
at http://localhost:3000/static/js/main.5626b1bf.js:2:174724
at http://localhost:3000/static/js/main.5626b1bf.js:2:390491
at $p (http://localhost:3000/static/js/main.5626b1bf.js:2:388981)
at qp (http://localhost:3000/static/js/main.5626b1bf.js:2:388735)
at Kp (http://localhost:3000/static/js/main.5626b1bf.js:2:389095)
at Jp (http://localhost:3000/static/js/main.5626b1bf.js:2:391018)
at u (http://localhost:3000/static/js/main.5626b1bf.js:2:331415)
at vc (http://localhost:3000/static/js/main.5626b1bf.js:2:307219)
at n (http://localhost:3000/static/js/main.5626b1bf.js:2:395066)

### Additional Information

```Text
This happens when using the GUI and trying to add a show to the queue.  Happens immediately after hitting the plus button
```

**Comment by drknss89** [comment]
got working thnx to discord,  changed my cli-default file from dubLang: eng to dubLang: [eng]
