### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by StrPlayer** [anidl/multi-downloader-nx#355]
### Program version

3.0.7 & 3.1.0

### Operating System

Windows

### Type

Gui

### Service

Crunchyroll

### Command used

N/A

### Show ID

N/A

### Episode

N/A

### Console Output

[INFO][ffmpeg Done]
Error occurred in handler for 'downloadItem': SyntaxError: Unexpected token 
    at JSON.parse (<anonymous>)
    at loadData (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.downloadArchive.js:163:21)
    at downloaded (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.downloadArchive.js:120:16)
    at Crunchy.<anonymous> (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\crunchy.js:1267:65)
    at step (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\crunchy.js:67:23)
    at Object.next (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\crunchy.js:48:53)
    at fulfilled (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\crunchy.js:39:58)
Appdata C:\Users\Star\AppData\Roaming

### Additional Information

```Text
It downloads one episode then throws this error
```

**Comment by izu-co** [comment]
Please try to delete the archive.json file in the config folder

**Comment by StrPlayer** [comment]
Worked thanks
