### ISSUE TITLE
[BUG]: MKVMerge not detected?

### ISSUE THREAD

**Issue by ChrisCrashX** [anidl/multi-downloader-nx#530]
### Program version

4.3.0

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

anidl.exe --service crunchy --srz GZJH3DJ8E -q 0 --dubLang eng --nosubs -e

### Show ID

GZJH3DJ8E

### Episode

1

### Console Output

```Shell
=== Multi Downloader NX 4.3.0 ===

[ERROR] [ERROR] YAMLParseError: Invalid escape sequence \Users\Sau at line 2, column 14:

mkvmerge: "C:\Users\SauceEXP\Documents\multi-downloader-nx-windows-cli 4.3.0\mu…
             ^

    at C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\composer.js:69:34
    at _onError (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\resolve-flow-scalar.js:10:42)
    at parseCharCode (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\resolve-flow-scalar.js:219:9)
    at doubleQuotedValue (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\resolve-flow-scalar.js:148:24)
    at Object.resolveFlowScalar (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\resolve-flow-scalar.js:22:21)
    at Object.composeScalar (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\compose-scalar.js:11:29)
    at composeNode (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\compose-node.js:24:34)
    at Object.resolveBlockMap (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\resolve-block-map.js:81:19)
    at resolveCollection (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\compose-collection.js:13:27)
    at Object.composeCollection (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\yaml@2.3.1\node_modules\yaml\dist\compose\compose-collection.js:47:16) {
  code: 'BAD_DQ_ESCAPE',
  pos: [ 42, 43 ],
  linePos: [ { line: 2, col: 14 }, { line: 2, col: 15 } ]
}
```

### Additional Information

The program was working with no problems up until 3 days ago... I'm certain I didn't change any directories for the config and I am more than positive I set the correct folder.

**Comment by HellsCrimson** [comment]
Looks like an escaping error
Can you try to escape the backslash in the path (put `\\` instead of `\`) in the file `bin-path.yml` of the config

**Comment by ChrisCrashX** [comment]
> Looks like an escaping error Can you try to escape the backslash in the path (put `\\` instead of `\`) in the file `bin-path.yml` of the config

That fixed it, I put \\ in-between every directory and it works again. Thank you so much!

**Comment by HellsCrimson** [comment]
Glad it helped

**Comment by AnimeDL** [comment]
Whoops! I forgot to respond to this, glad you got your help though, I'll go ahead and mark this as closed
