### ISSUE TITLE
[BUG]: Cannot read properties of undefined (reading 'href')

### ISSUE THREAD

**Issue by THS-Shiniri** [anidl/multi-downloader-nx#591]
### Program version

4.4.4

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

Ive Used The Gui

### Show ID

GDKHZEJ0K

### Episode

10

### Console Output

```Shell
[DEBUG] Got resolve options: {"id":"GDKHZEJ0K","q":0,"e":",10","dubLang":["jpn"],"dlsubs":["all"],"fileName":"[${service}] ${showTitle} - S${season}E${episode} [${height}p]","dlVideoOnce":false,"all":false,"but":false,"noaudio":false,"novids":false}

...

\multi-downloader-nx\lib\crunchy.js:1682
                if (item.__links__.streams.href) {
                                           ^

TypeError: Cannot read properties of undefined (reading 'href')
    at C:\Users\Leuth\AniDL\multi-downloader-nx\lib\crunchy.js:1682:44
    at Array.forEach (<anonymous>)
    at Crunchy.itemSelectMultiDub (C:\Users\Leuth\AniDL\multi-downloader-nx\lib\crunchy.js:1646:25)
    at Crunchy.<anonymous> (C:\Users\Leuth\AniDL\multi-downloader-nx\lib\crunchy.js:1630:35)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Leuth\AniDL\multi-downloader-nx\lib\crunchy.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by THS-Shiniri** [comment]
Idk what it was a restart fixed it. Closed.
