### ISSUE TITLE
[BUG]: RangeError: index out of range

### ISSUE THREAD

**Issue by werewolf004** [anidl/multi-downloader-nx#665]
### Program version

4.7.1

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

.\aniDL.exe --service crunchy --series %series% -e %episode% --partsize 50 --dlsubs "fr" --chapters --defaultAudio "jpn" --defaultSub "fra" --fileName '${showTitle} Season ${season} Episode ${episode}'

### Show ID

GXJHM3GNX

### Episode

3

### Console Output

```Shell
[Z:GXJHM3GNX] Train to the End of the World (Seasons: 1, EPs: 3) [SIMULCAST, SUB]
  - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [S:G6K5CN12N] Train to the End of the World (Season: 1) [SIMULCAST, SUB]
    - Versions: ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
[E1] Train to the End of the World - Season 1 - Down the Escalator to Dark Nerima [☆ Japanese]
[E2] Train to the End of the World - Season 1 - Suppose, Maybe, Presumably [☆ Japanese]
[E3] Train to the End of the World - Season 1 - Short, Happy, and Easy [☆ Japanese]

------------------------------

[S1E3] - Short, Happy, and Easy [✓ Japanese]
Requesting: [G14U411EE] Train to the End of the World - 3 - Short, Happy, and Easy
Chapter request successful
[ERROR] 403: Forbidden
[ERROR] Non-DRM Request Stream URLs FAILED!
Selecting raw stream
Full stream found! (✓1: drm_adaptive_dash/jpn/- )
Full stream found! ( 2: drm_download_dash/jpn/- )
Downloading video...
Playlists URL: https://pl.crunchyroll.com/evs3/478216c4d2b7eed5135923f97aad3f15/assets/p/8fe53590e438f64afff168ddc2d05afc_,5503447.mp4,5503448.mp4,5503446.mp4,5503444.mp4,5503445.mp4,.urlset/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy80NzgyMTZjNGQyYjdlZWQ1MTM1OTIzZjk3YWFkM2YxNS9hc3NldHMvcC84ZmU1MzU5MGU0MzhmNjRhZmZmMTY4ZGRjMmQwNWFmY18sNTUwMzQ0Ny5tcDQsNTUwMzQ0OC5tcDQsNTUwMzQ0Ni5tcDQsNTUwMzQ0NC5tcDQsNTUwMzQ0NS5tcDQsLnVybHNldC9tYW5pZmVzdC5tcGQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTM3MTk3NzR9fX1dfQ__&Signature=kbUSC4hvqUJf5-Z-En1Lc5AsnflV58KiT5NPYj6qwg3mwXxJwCMW3wAZIFg0Ve4M46XlIP-VSJK4RZb1EXW07sZkEcKmVc3C2qezKwRdVCzSfO2WAJvUoV0oNp5MWAI64tcPZGHZwPa7FfuFIiz4i2XvIRJ0IVwECaLvul2Qk3Y5GIYDR8BXe-NmQKghG9e3I9muDKltUq1wDf8Gg4muML6Rbm12E8jd1hOMrlBhZJvoECdDmywYtfuOnH~FNttHnBzw5LWwDGpQCa3me24WK8tCnbDtCPWwQcfyPIhIKos4VdRrIRSODt-9h5FfLgsulZVpoWnwP15lb1DphoJNzg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (drm_adaptive_dash/jpn/-)
Servers available:
        a-vrv.akamaized.net
        fy.v.vrv.co
Available Video Qualities:
        [1] 428x240 (488KiB/s)
        [2] 640x360 (973KiB/s)
        [3] 848x480 (1950KiB/s)
        [4] 1280x720 (3894KiB/s)
        [5] 1920x1080 (7797KiB/s)
Available Audio Qualities:
        [1] 64kB/s
        [2] 96kB/s
        [3] 128kB/s
Selected quality:
        Video: 1920x1080 (7797KiB/s)
        Audio: 128kB/s
        Server: a-vrv.akamaized.net
Stream URL: https://a-vrv.akamaized.net/evs3/478216c4d2b7eed5135923f97aad3f15/assets/p/8fe53590e438f64afff168ddc2d05afc_,5503447.mp4,5503448.mp4,5503446.mp4,5503444.mp4,5503445.mp4
Total parts in video stream: 355 (8*50)
Saving stream to «K:\multi-downloader-nx-windows-cli\videos\temp-G14U411EE.video.enc.m4s»...
Download and save init part...
Init part downloaded.
50 of 355 parts downloaded [14%] (35s | 38Mb/s)
100 of 355 parts downloaded [28%] (28s | 36Mb/s)
150 of 355 parts downloaded [42%] (23s | 36Mb/s)
200 of 355 parts downloaded [56%] (17s | 36Mb/s)
250 of 355 parts downloaded [70%] (11s | 36Mb/s)
300 of 355 parts downloaded [85%] (6s | 37Mb/s)
350 of 355 parts downloaded [99%] (1s | 37Mb/s)
355 of 355 parts downloaded [100%] (0s | 37Mb/s)
Total parts in audio stream: 355 (8*50)
Saving stream to «K:\multi-downloader-nx-windows-cli\videos\temp-G14U411EE.audio.enc.m4s»...
Download and save init part...
Init part downloaded.
50 of 355 parts downloaded [14%] (29s | 0.72Mb/s)
100 of 355 parts downloaded [28%] (24s | 0.72Mb/s)
150 of 355 parts downloaded [42%] (19s | 0.72Mb/s)
200 of 355 parts downloaded [56%] (14s | 0.72Mb/s)
250 of 355 parts downloaded [70%] (10s | 0.73Mb/s)
300 of 355 parts downloaded [85%] (5s | 0.73Mb/s)
350 of 355 parts downloaded [99%] (0s | 0.71Mb/s)
355 of 355 parts downloaded [100%] (0s | 0.71Mb/s)
Decryption Needed, attempting to decrypt
C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\protobufjs@7.2.6\node_modules\protobufjs\src\reader.js:13
    return RangeError("index out of range: " + reader.pos + " + " + (writeLength || 1) + " > " + reader.len);
           ^

RangeError: index out of range: 103 + 1284340 > 3260
    at indexOutOfRange (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\protobufjs@7.2.6\node_modules\protobufjs\src\reader.js:13:12)
    at Reader.read_bytes [as bytes] (C:\snapshot\multi-downloader-nx\lib\node_modules\.pnpm\protobufjs@7.2.6\node_modules\protobufjs\src\reader.js:310:15)
    at Object.decode (C:\snapshot\multi-downloader-nx\lib\modules\license_protocol.js)
    at new Session (C:\snapshot\multi-downloader-nx\lib\modules\license.js)
    at C:\snapshot\multi-downloader-nx\lib\modules\widevine.js
    at Generator.next (<anonymous>)
    at C:\snapshot\multi-downloader-nx\lib\modules\widevine.js
    at new Promise (<anonymous>)
    at C:\snapshot\multi-downloader-nx\lib\modules\widevine.js
    at getKeys (C:\snapshot\multi-downloader-nx\lib\modules\widevine.js)

Node.js v18.18.2
```

### Additional Information

Working fine monday and not working today nothing change don't know why, I try to upgrde from 4.7.0 to 4.7.1 and same problem

**Comment by Jaynator495** [comment]
As it works for me, I'm pretty sure this means an issue with your CDM

**Comment by werewolf004** [comment]
> As it works for me, I'm pretty sure this means an issue with your CDM

What you mean by CDM ?
A friend test and it work yes on his computer, don't know why, nothing have change since the last time, only powershell as been upgraded to 7.4.2 since the last time it works

**Comment by Jaynator495** [comment]
I mean what you put in the ./widevine/ folder. There is likely something wrong with those files

**Comment by werewolf004** [comment]
> I mean what you put in the ./widevine/ folder. There is likely something wrong with those files

It's weird, nothing change since tuesday, directory has not been upgraded
My friend got the same widevine folder / files and it work for him

**Comment by werewolf004** [comment]
I close this bug, it came from the widevine keys, i dump my own keys instead using the one of my friend and it work now. thanks

**Comment by Jaynator495** [comment]
Glad you figured it out :)
