### ISSUE TITLE
Je n'arrive pas à télécharger des épisodes sur crunchyroll

### ISSUE THREAD

**Issue by olivier-fog-dev** [anidl/multi-downloader-nx#795]
### Program version

5.1.5

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

AniDl --service "crunchy" -s "G60X2WMWR" -e "GREX7JW8Y" -q "0" --chapters --dubLang "jpn" --allDubs --fileName "${show Title}_S${season}E${episode}_En mille morceaux ~ Quelqu'un regarde ~"

### Show ID

G60X2WMWR

### Episode

1

### Console Output

```Shell
Requesting: [GREX7JW8Y] Mob Psycho 100 II - 1 - Ripped Apart ~Someone Is Watching~
Chapter request successful
[WARN] Decryption not enabled!
[WARN] No full streams found!
[ERROR] Unable to download selected episode 1
```

**Comment by XxUnkn0wnxX** [comment]
not a bug, you need to setup decryption. you need widevine folder with `device_client_id_blob` & `device_private_key`
sadly you won't find anyone sharing these as you need to get these yourself. via dumping keys from a rooted android or this method here via a virtual android device like I did.
Guide:
https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio

CR, Hidive etc require valid CDM keys for content decryption.
for the dumper:
https://github.com/lollolong/dumper
https://github.com/Diazole/dumper

frida-server:
https://github.com/frida/frida/releases

android studio:
https://developer.android.com/studio

your PC will need to be somewhat decent to run a virtual android device, this is akin to running a virtual machine.

**Comment by olivier-fog-dev** [comment]
Bonjour, et merci pour votre aide. Je suis a nouveau coincé à se niveau:

voici se qui est noté sur la console : 

C:\Users\fog09\Downloads\multi-downloader-nx-windows-cli\multi-downloader-nx-windows-x64-cli\dumper-main\dumper-main>Python dump_keys.py
Traceback (most recent call last):
  File "C:\Users\fog09\Downloads\multi-downloader-nx-windows-cli\multi-downloader-nx-windows-x64-cli\dumper-main\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "C:\Users\fog09\Downloads\multi-downloader-nx-windows-cli\multi-downloader-nx-windows-x64-cli\dumper-main\dumper-main\Helpers\Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "C:\Users\fog09\Downloads\multi-downloader-nx-windows-cli\multi-downloader-nx-windows-x64-cli\dumper-main\dumper-main\Helpers\wv_proto2_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\fog09\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

C:\Users\fog09\Downloads\multi-downloader-nx-windows-cli\multi-downloader-nx-windows-x64-cli\dumper-main\dumper-main>

Je ne comprend pas se qu'il faut faire. Merci de votre retour.

**Comment by stratumadev** [comment]
Better error handeling was build in for CDMs and Shaka/mp4decrypt.
